//   Messages used by the MCOMP program.
//
msg access_none
  lan english -def
    No access specified.  Some access is required.
msg adrreg_err
  lan english -def
    Error in ADDRESS REGION statement.
msg adrreg_name_none
  lan english -def
    Unable to get address region name.
msg adrreg_opt_bad
  lan english -def
    Invalid ADDRESS REGION option.
msg accty_err
  lan english -def
    Invalid access type.
msg accty_npar
  lan english -def
    Parent does not have this access type.  Only access types that the
    parent has can be added.
msg adr_err
  lan english -def
    Error in ADRSPACE statement.
msg adr_name_none
  lan english -def
    Unable to get address space name.
msg adr_opt_bad
  lan english -def
    Invalid adrspace option.
msg end_len_diff
  lan english -def
    Mismatch between address length and end address.
msg end_len_none
  lan english -def
    Missing end address or length.
msg indent_bad
  lan english -def
    Invalid indentation of %p1i found.  Indentation must be an even number
    of blanks.
msg mem_err
  lan english -def
    Error in MEMORY statement.
msg mem_name_none
  lan english -def
    Unable to get memory name.
msg mem_opt_bad
  lan english -def
    Invalid MEMORY option.
msg memreg_err
  lan english -def
    Error in MEMORY REGION statement.
msg memreg_name_none
  lan english -def
    Unable to get memory region name.
msg memreg_nfound
  lan english -def
    Memory region not previously define.
msg memreg_opt_bad
  lan english -def
    Invalid MEMORY REGION option.
msg statement_bad
  lan english -def
    Invalid statement.
msg statement_err
  lan english -def
    INTERNAL ERROR: Attempt to parse a new statement when a syntax error
    was previously encountered.
msg statement_subordinate
  lan english -def
    A subordinate statement is not allowed here.
msg type_bad
  lan english -def
    Invalid TYPE statement.
msg type_def_bad
  lan english -def
    Not a valid data type definition or reference.
msg type_int_bad
  lan english -def
    Invalid INTEGER data type parameter.
msg type_name_bad
  lan english -def
    Not a valid data type name.
